-- =====================================================================
-- AfriStock — Phase 3 (compléments) : pertes + inventaires
-- =====================================================================

CREATE TABLE stock_losses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL,
    site_id     BIGINT NOT NULL,
    type        VARCHAR(255) NOT NULL,
    quantity    INTEGER NOT NULL,
    reason      VARCHAR(255),
    declared_at TIMESTAMP,
    user_id     BIGINT,
    company_id  BIGINT NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_losses_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_losses_site    FOREIGN KEY (site_id)    REFERENCES sites (id),
    CONSTRAINT fk_losses_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_losses_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_stock_losses_company ON stock_losses (company_id);

CREATE TABLE inventory_sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    BIGINT NOT NULL,
    note       VARCHAR(255),
    counted_at TIMESTAMP,
    user_id    BIGINT,
    company_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_inv_sessions_site    FOREIGN KEY (site_id)    REFERENCES sites (id),
    CONSTRAINT fk_inv_sessions_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_inv_sessions_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_inv_sessions_company ON inventory_sessions (company_id);

CREATE TABLE inventory_lines (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        BIGINT NOT NULL,
    product_id        BIGINT NOT NULL,
    previous_quantity INTEGER NOT NULL,
    counted_quantity  INTEGER NOT NULL,
    company_id        BIGINT NOT NULL,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    CONSTRAINT fk_inv_lines_session FOREIGN KEY (session_id) REFERENCES inventory_sessions (id),
    CONSTRAINT fk_inv_lines_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_inv_lines_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_inv_lines_company ON inventory_lines (company_id);
CREATE INDEX idx_inv_lines_session ON inventory_lines (session_id);
