-- =====================================================================
-- AfriStock — Phase 5 : Achats (commandes fournisseurs)
-- =====================================================================

CREATE TABLE purchase_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference     VARCHAR(255) NOT NULL,
    supplier_id   BIGINT NOT NULL,
    site_id       BIGINT NOT NULL,
    status        VARCHAR(255) NOT NULL,
    order_date    TIMESTAMP,
    received_date TIMESTAMP,
    total_amount  FLOAT8 NOT NULL DEFAULT 0,
    amount_paid   FLOAT8 NOT NULL DEFAULT 0,
    user_id       BIGINT,
    company_id    BIGINT NOT NULL,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_po_site     FOREIGN KEY (site_id)     REFERENCES sites (id),
    CONSTRAINT fk_po_user     FOREIGN KEY (user_id)     REFERENCES users (id),
    CONSTRAINT fk_po_company  FOREIGN KEY (company_id)  REFERENCES companies (id)
);
CREATE INDEX idx_po_company ON purchase_orders (company_id);

CREATE TABLE purchase_order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    product_id        BIGINT NOT NULL,
    quantity          INTEGER NOT NULL,
    unit_cost         FLOAT8 NOT NULL,
    line_total        FLOAT8 NOT NULL,
    company_id        BIGINT NOT NULL,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    CONSTRAINT fk_poi_order   FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id),
    CONSTRAINT fk_poi_product FOREIGN KEY (product_id)        REFERENCES products (id),
    CONSTRAINT fk_poi_company FOREIGN KEY (company_id)        REFERENCES companies (id)
);
CREATE INDEX idx_poi_company ON purchase_order_items (company_id);
CREATE INDEX idx_poi_order   ON purchase_order_items (purchase_order_id);
