-- =====================================================================
-- AfriStock — Phase 6 : Comptabilité / trésorerie (mono-entrée)
-- =====================================================================

CREATE TABLE accounting_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(255) NOT NULL,
    account     VARCHAR(255) NOT NULL,
    category    VARCHAR(255),
    amount      FLOAT8 NOT NULL,
    entry_date  DATE NOT NULL,
    description VARCHAR(255),
    user_id     BIGINT,
    company_id  BIGINT NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_acc_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_acc_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_acc_company ON accounting_entries (company_id);
CREATE INDEX idx_acc_date    ON accounting_entries (entry_date);
