-- =====================================================================
-- AfriStock — Phase 7 : Ressources humaines
-- =====================================================================

CREATE TABLE employees (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    position      VARCHAR(255),
    contract_type VARCHAR(255),
    hire_date     DATE,
    base_salary   FLOAT8,
    phone         VARCHAR(255),
    email         VARCHAR(255),
    site_id       BIGINT,
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    company_id    BIGINT NOT NULL,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT fk_employees_site    FOREIGN KEY (site_id)    REFERENCES sites (id),
    CONSTRAINT fk_employees_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_employees_company ON employees (company_id);

CREATE TABLE leaves (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    type        VARCHAR(255) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    status      VARCHAR(255) NOT NULL,
    reason      VARCHAR(255),
    company_id  BIGINT NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_leaves_employee FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT fk_leaves_company  FOREIGN KEY (company_id)  REFERENCES companies (id)
);
CREATE INDEX idx_leaves_company ON leaves (company_id);

CREATE TABLE attendances (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    work_date   DATE NOT NULL,
    present     BOOLEAN NOT NULL DEFAULT TRUE,
    note        VARCHAR(255),
    company_id  BIGINT NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_attendance_employee FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT fk_attendance_company  FOREIGN KEY (company_id)  REFERENCES companies (id),
    CONSTRAINT uk_attendance_employee_day UNIQUE (employee_id, work_date)
);
CREATE INDEX idx_attendances_company ON attendances (company_id);
