-- =====================================================================
-- AfriStock — Phase 9 : Abonnements SaaS
-- =====================================================================

CREATE TABLE subscription_plans (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(255) NOT NULL UNIQUE,
    name          VARCHAR(255) NOT NULL,
    monthly_price FLOAT8 NOT NULL DEFAULT 0,
    max_users     INTEGER,
    description   VARCHAR(255),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);

CREATE TABLE subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL UNIQUE,
    plan_name  VARCHAR(255),
    status     VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date   DATE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_subscriptions_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_subscriptions_company ON subscriptions (company_id);
