-- =====================================================================
-- AfriStock — Schéma initial (Lot 1)
-- Reflète l'état existant du domaine : entreprises, utilisateurs,
-- catégories, produits, mouvements de stock.
--
-- Sur une base existante (créée auparavant par ddl-auto=update), Flyway
-- effectue un "baseline" et NE rejoue PAS ce script.
-- Sur une base neuve, ce script crée tout le schéma.
-- =====================================================================

CREATE TABLE companies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    email       VARCHAR(255) NOT NULL UNIQUE,
    phone       VARCHAR(255),
    city        VARCHAR(255),
    created_at  TIMESTAMP
);

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    role        VARCHAR(255),
    company_id  BIGINT NOT NULL,
    CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    company_id  BIGINT NOT NULL,
    CONSTRAINT fk_categories_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE TABLE products (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference        VARCHAR(255) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    description      VARCHAR(255),
    purchase_price   FLOAT8,
    sale_price       FLOAT8,
    current_quantity INTEGER,
    min_threshold    INTEGER,
    unit             VARCHAR(255),
    category_id      BIGINT NOT NULL,
    company_id       BIGINT NOT NULL,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_products_company  FOREIGN KEY (company_id)  REFERENCES companies (id)
);

CREATE TABLE stock_movements (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL,
    type        VARCHAR(255) NOT NULL,
    quantity    INTEGER NOT NULL,
    reason      VARCHAR(255),
    created_at  TIMESTAMP,
    company_id  BIGINT NOT NULL,
    user_id     BIGINT,
    CONSTRAINT fk_movements_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_movements_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_movements_user    FOREIGN KEY (user_id)    REFERENCES users (id)
);

-- Index utiles pour l'isolation multi-tenant (filtrage systématique par company_id).
CREATE INDEX idx_categories_company       ON categories (company_id);
CREATE INDEX idx_products_company         ON products (company_id);
CREATE INDEX idx_stock_movements_company  ON stock_movements (company_id);
CREATE INDEX idx_users_company            ON users (company_id);
