-- =====================================================================
-- AfriStock — Fondations SaaS (Lot 1)
--   * Statut des entreprises (actif / suspendu) + audit
--   * Super-Administrateur sans entreprise (company_id devient nullable)
--   * Table des fonctionnalités (feature flags globaux)
-- =====================================================================

-- 1. Statut + date de mise à jour des entreprises
ALTER TABLE companies ADD COLUMN status     VARCHAR(255) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE companies ADD COLUMN updated_at TIMESTAMP;

-- 2. Le Super-Administrateur n'appartient à aucune entreprise
ALTER TABLE users ALTER COLUMN company_id DROP NOT NULL;

-- 3. Fonctionnalités (feature flags)
CREATE TABLE features (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    category    VARCHAR(255),
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);
