-- =====================================================================
-- AfriStock — Phase 2 : Sites (boutiques / entrepôts)
-- =====================================================================

CREATE TABLE sites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(255) NOT NULL,
    address     VARCHAR(255),
    city        VARCHAR(255),
    phone       VARCHAR(255),
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    company_id  BIGINT NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_sites_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE INDEX idx_sites_company ON sites (company_id);
