-- =====================================================================
-- AfriStock — Phase 2 : Fournisseurs
-- =====================================================================

CREATE TABLE suppliers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255),
    email        VARCHAR(255),
    phone        VARCHAR(255),
    address      VARCHAR(255),
    city         VARCHAR(255),
    notes        VARCHAR(1000),
    active       BOOLEAN NOT NULL DEFAULT TRUE,
    company_id   BIGINT NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT fk_suppliers_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE INDEX idx_suppliers_company ON suppliers (company_id);
