-- =====================================================================
-- AfriStock — Phase 2 : Clients
-- =====================================================================

CREATE TABLE customers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    type           VARCHAR(255) NOT NULL,
    email          VARCHAR(255),
    phone          VARCHAR(255),
    address        VARCHAR(255),
    city           VARCHAR(255),
    credit_limit   FLOAT8 NOT NULL DEFAULT 0,
    loyalty_points INTEGER NOT NULL DEFAULT 0,
    notes          VARCHAR(1000),
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    company_id     BIGINT NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT fk_customers_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE INDEX idx_customers_company ON customers (company_id);
