-- =====================================================================
-- AfriStock — Phase 2 : Produits enrichis (marques, variantes, codes-barres, image)
-- =====================================================================

-- 1. Marques
CREATE TABLE brands (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    company_id  BIGINT NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_brands_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_brands_company ON brands (company_id);

-- 2. Nouvelles colonnes sur les produits
ALTER TABLE products ADD COLUMN barcode   VARCHAR(255);
ALTER TABLE products ADD COLUMN image_url VARCHAR(255);
ALTER TABLE products ADD COLUMN brand_id  BIGINT;
ALTER TABLE products ADD CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands (id);

-- 3. Variantes de produit
CREATE TABLE product_variants (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT NOT NULL,
    name             VARCHAR(255) NOT NULL,
    barcode          VARCHAR(255),
    price_adjustment FLOAT8 NOT NULL DEFAULT 0,
    company_id       BIGINT NOT NULL,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    CONSTRAINT fk_variants_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_variants_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_variants_company ON product_variants (company_id);
CREATE INDEX idx_variants_product ON product_variants (product_id);
