-- =====================================================================
-- AfriStock — Phase 3 : Stock multi-sites (niveaux par site + transferts)
-- =====================================================================

-- 1. Niveaux de stock par site
CREATE TABLE stock_levels (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL,
    site_id     BIGINT NOT NULL,
    quantity    INTEGER NOT NULL DEFAULT 0,
    company_id  BIGINT NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_stock_levels_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_stock_levels_site    FOREIGN KEY (site_id)    REFERENCES sites (id),
    CONSTRAINT fk_stock_levels_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT uk_stock_product_site   UNIQUE (product_id, site_id)
);
CREATE INDEX idx_stock_levels_company ON stock_levels (company_id);

-- 2. Transferts de stock entre sites
CREATE TABLE stock_transfers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL,
    from_site_id   BIGINT NOT NULL,
    to_site_id     BIGINT NOT NULL,
    quantity       INTEGER NOT NULL,
    reason         VARCHAR(255),
    transferred_at TIMESTAMP,
    user_id        BIGINT,
    company_id     BIGINT NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT fk_transfers_product   FOREIGN KEY (product_id)   REFERENCES products (id),
    CONSTRAINT fk_transfers_from_site FOREIGN KEY (from_site_id) REFERENCES sites (id),
    CONSTRAINT fk_transfers_to_site   FOREIGN KEY (to_site_id)   REFERENCES sites (id),
    CONSTRAINT fk_transfers_user      FOREIGN KEY (user_id)      REFERENCES users (id),
    CONSTRAINT fk_transfers_company   FOREIGN KEY (company_id)   REFERENCES companies (id)
);
CREATE INDEX idx_stock_transfers_company ON stock_transfers (company_id);
