-- =====================================================================
-- AfriStock — Phase 4 : Ventes & caisse
-- =====================================================================

CREATE TABLE sales (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference      VARCHAR(255) NOT NULL,
    site_id        BIGINT NOT NULL,
    customer_id    BIGINT,
    user_id        BIGINT,
    sale_type      VARCHAR(255) NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    sale_date      TIMESTAMP,
    total_amount   FLOAT8 NOT NULL DEFAULT 0,
    amount_paid    FLOAT8 NOT NULL DEFAULT 0,
    company_id     BIGINT NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT fk_sales_site     FOREIGN KEY (site_id)     REFERENCES sites (id),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_sales_user     FOREIGN KEY (user_id)     REFERENCES users (id),
    CONSTRAINT fk_sales_company  FOREIGN KEY (company_id)  REFERENCES companies (id)
);
CREATE INDEX idx_sales_company ON sales (company_id);
CREATE INDEX idx_sales_date    ON sales (sale_date);

CREATE TABLE sale_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id     BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    quantity    INTEGER NOT NULL,
    unit_price  FLOAT8 NOT NULL,
    line_total  FLOAT8 NOT NULL,
    company_id  BIGINT NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_sale_items_sale    FOREIGN KEY (sale_id)    REFERENCES sales (id),
    CONSTRAINT fk_sale_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_sale_items_company FOREIGN KEY (company_id) REFERENCES companies (id)
);
CREATE INDEX idx_sale_items_company ON sale_items (company_id);
CREATE INDEX idx_sale_items_sale    ON sale_items (sale_id);
