services:
  - type: web
    name: afristock
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false   # jdbc:postgresql://<host>:<port>/afristock (Internal Database URL de la base)
      - key: SPRING_DATASOURCE_USERNAME
        sync: false   # ex: afristock
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false   # mot de passe de la base Render
      - key: PORT
        value: "8080"

databases:
  - name: afristock-db
    plan: free
    databaseName: afristock
    user: afristock
